BurguerApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('catalog_BurguerApp.urls')),
    path('auth/', include('auth_BurguerApp.urls')),
    path('', views.home, name='home'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('profile/', views.user_profile, name='user_profile'),
]

handler404 = 'BurguerApp.views.custom_page_not_found'
handler500 = 'BurguerApp.views.custom_error'
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog_BurguerApp/urls.py
from django.http import request;
from django.urls import path;
from django.views.generic.base import RedirectView
from . import views

app_name = 'catalog_BurguerApp'

urlpatterns = [

    path("", RedirectView.as_view(pattern_name='auth_BurguerApp:login_view'), name='home'),
    path('produtos/', views.product_list, name='product_list'),
    path('produtos/<int:id>/', views.product_detail, name='product_detail'),
    path('produtos/criar/', views.product_create, name='product_create'),
    path('produtos/<int:id>/atualizar/', views.product_update, name='product_update'),
    path('produtos/<int:id>/excluir/', views.product_delete, name='product_delete'),

    path('categorias/', views.category_list, name='category_list'),
    path('categorias/<int:id>/', views.category_detail, name='category_detail'),
    path('categorias/criar/', views.category_create, name='category_create'),
    path('categorias/<int:id>/atualizar/', views.category_update, name='category_update'),
    path('categorias/<int:id>/excluir/', views.category_delete, name='category_delete'),
]

catalog_BurguerApp/models.py
from django.db import models
from django.db.models import CharField, DateTimeField, AutoField, ForeignKey, DecimalField, PositiveIntegerField, BooleanField, URLField, ImageField;
from auth_BurguerApp.models import User
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

class Categories(models.Model):
    id = AutoField(primary_key=True)
    name = CharField(max_length=255, unique=True, verbose_name='Nome da Categoria')
    image = ImageField(upload_to='post_img/categories', blank=True, null=True)
    path =  URLField(max_length=2000, verbose_name='Caminho da Imagem', blank=True, null=True)
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)
    
    @mark_safe
    def figure(self):
        return f'<img width="30px" src="/media/{self.image}">'

    def __str__(self):
        return self.name


class Products(models.Model):
    id = AutoField(primary_key=True)
    name = CharField(max_length=255, verbose_name='Nome do Produto')
    price = DecimalField(max_digits=10, decimal_places=2, verbose_name='Preço')
    category = ForeignKey(
        Categories,
        on_delete=models.SET_NULL,
        verbose_name='Categoria',
        null=True,
        related_name="products"
        )
    image = ImageField(upload_to='post_img/products', blank=True, null=True)
    path = URLField(max_length=2000, verbose_name='Caminho da Imagem', blank=True, null=True)
    offer = BooleanField(default=False, verbose_name='Disponibilidade')
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)
    
    @mark_safe
    def figure(self):
        return f'<img width="30px" src="/media/{self.image}">'

    def __str__(self):
        return self.name
    
    def clean(self):
        if self.price <= 0:
            raise ValidationError("O preço deve ser um numero positivo")

class Orders(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('CONFIRMED', 'Confirmed'),
        ('DELIVERED', 'Delivered'),
        ('CANCELED', 'Canceled'),
    ]

    id = AutoField(primary_key=True)
    user = ForeignKey(User, on_delete=models.CASCADE, related_name="orders")
    products = models.ManyToManyField(Products, through='OrderItem')
    status = CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order {self.id} - {self.user.name}"


class OrderItem(models.Model):
    order = ForeignKey(Orders, on_delete=models.CASCADE, related_name="order_items")
    product = ForeignKey(Products, on_delete=models.CASCADE)
    quantity = PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} (Order {self.order.id})"
    

catalog_BurguerApp/forms.py
from django import forms
from .models import Products, Categories

class ProductForm(forms.ModelForm):
    offer = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )
    path = forms.URLField(
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-control'}),
        label="URL da Imagem",
        help_text="Insira a URL de uma imagem externa para o produto",
    )

    class Meta:
        model = Products
        fields = ['name', 'price', 'category', 'path', 'offer']

class CategoryForm(forms.ModelForm):
    path = forms.URLField(
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-control'}),
        label="URL da Categoria",
        help_text="Insira a URL de uma imagem externa para a categoria",
    )

    class Meta:
        model = Categories
        fields = ['name', 'path']

catalog_BurguerApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .models import Products, Categories
from .forms import ProductForm, CategoryForm
from django.contrib.auth.decorators import login_required, user_passes_test

def is_manager(user):
    return user.is_staff  

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')  
def product_list(req):
    if req.method == "GET":
        products = Products.objects.all()
        if req.GET.get('format') == 'json':
            product_list = list(products.values('id', 'name', 'price', 'category__name', 'path', 'offer'))
            return JsonResponse({"products": product_list})
        return render(req, 'products/list.html', {"products": products})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def product_create(req):
    if req.method == "POST":
        form = ProductForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect('catalog_BurguerApp:product_list')
    else:
        form = ProductForm()
    return render(req, 'products/form.html', {'form': form})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def product_detail(request, id):
    product = get_object_or_404(Products, id=id)
    return render(request, 'products/detail.html', {'product': product})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def product_update(request, id):
    product = get_object_or_404(Products, id=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('catalog_BurguerApp:product_detail', id=product.id)
    else:
        form = ProductForm(instance=product)
    return render(request, 'products/update.html', {'form': form, 'product': product})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def product_delete(request, id):
    product = get_object_or_404(Products, id=id)
    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Produto deletado com sucesso!')
        return redirect('catalog_BurguerApp:product_list')
    return render(request, 'products/delete.html', {'product': product})



@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def category_list(request):
    categories = Categories.objects.all()
    return render(request, 'categories/list.html', {'categories': categories})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def category_detail(request, id):
    category = get_object_or_404(Categories, id=id)
    return render(request, 'categories/detail.html', {'category': category})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalog_BurguerApp:category_list')
    else:
        form = CategoryForm()
    return render(request, 'categories/form.html', {'form': form})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def category_update(request, id):
    category = get_object_or_404(Categories, id=id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('catalog_BurguerApp:category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'categories/update.html', {'form': form, 'category': category})

@login_required(login_url='/auth/login')
@user_passes_test(is_manager, login_url='/')
def category_delete(request, id):
    category = get_object_or_404(Categories, id=id)
    if request.method == 'POST':
        category.delete()
        return redirect('catalog_BurguerApp:category_list')
    return render(request, 'categories/delete.html', {'category': category})

catalog_BurguerApp/templates/products/delete.html
{% extends "base.html" %}

{% block 'titulo' %}Excluir Produto{% endblock %}

{% block 'content' %}
    <h1>Excluir Produto</h1>
    <p>Tem certeza de que deseja excluir o produto "{{ product.name }}"?</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Sim, excluir</button>
        <a href="{% url 'catalog_BurguerApp:product_detail' product.id %}" class="btn btn-secondary">Cancelar</a>
    </form>
{% endblock %}

catalog_BurguerApp/templates/products/detail.html
{% extends "base.html" %}

{% block 'titulo' %}Detalhes do Produto{% endblock %}

{% block 'content' %}
<div class="container mt-4">
    <h2>Detalhes do Produto</h2>

    <table class="table">
        <tr>
            <th>Nome:</th>
            <td>{{ product.name }}</td>
        </tr>
        <tr>
            <th>Preço:</th>
            <td>R$ {{ product.price|floatformat:2 }}</td>
        </tr>
        <tr>
            <th>Categoria:</th>
            <td>{{ product.category }}</td>
        </tr>
        <tr>
            <th>Oferta:</th>
            <td>
                {% if product.offer %}
                <span class="badge bg-success">Sim</span>
                {% else %}
                <span class="badge bg-secondary">Não</span>
                {% endif %}
            </td>
        </tr>
    </table>
    <a href="{% url 'catalog_BurguerApp:product_update' product.id %}" class="btn btn-primary">Editar</a>
    <a href="{% url 'catalog_BurguerApp:product_delete' product.id %}" class="btn btn-danger">Excluir</a>
    <a href="{% url 'catalog_BurguerApp:product_list' %}" class="btn btn-secondary">Voltar à Lista de Produtos</a>
</div>
{% endblock %}

catalog_BurguerApp/templates/products/form.html
{% extends "base.html" %}

{% load custom_filters %}

{% block 'titulo' %}Criar Novo Produto{% endblock %}

{% block 'content' %}
<h1 class="mb-4">Criar Novo Produto</h1>

<form method="POST">
  {% csrf_token %}
  {% for field in form %}
  <div class="mb-3">
    {% if field.name == 'offer' %}
    <div class="form-check form-switch">
      {{ field|add_class:"form-check-input" }}
      <label class="form-check-label" for="{{ field.id_for_label }}">
        Disponível
      </label>
      {% if field.help_text %}
      <div class="form-text">{{ field.help_text }}</div>
      {% endif %}
    </div>
    {% else %}
    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
    {{ field|add_class:"form-control" }}
    {% if field.help_text %}
    <div class="form-text">{{ field.help_text }}</div>
    {% endif %}
    {% endif %}
    
    {% for error in field.errors %}
    <div class="invalid-feedback d-block">{{ error }}</div>
    {% endfor %}
  </div>
  {% endfor %}
  
  <button type="submit" class="btn btn-primary">Criar Produto</button>
  <a href="{% url 'catalog_BurguerApp:product_list' %}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}

catalog_BurguerApp/templates/products/list.html
{% extends "base.html" %}

{% block 'titulo' %}Lista de Produtos{% endblock %}

{% block 'content' %}
<h1 class="mb-4">Produtos Disponíveis</h1>

{% if products %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Preço</th>
                <th>Categoria</th>
                <th>Ofertas</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td><a href="{% url 'catalog_BurguerApp:product_detail' product.id %}">{{ product.name }}</a></td>
                    <td>R$ {{ product.price|floatformat:2 }}</td>
                    <td>{{ product.category }}</td>
                    <td>
                        {% if product.offer %}
                            <span class="badge bg-success">Sim</span>
                        {% else %}
                            <span class="badge bg-secondary">Não</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'catalog_BurguerApp:product_update' product.id %}" class="btn btn-sm btn-primary">Editar</a>
                        <a href="{% url 'catalog_BurguerApp:product_delete' product.id %}" class="btn btn-sm btn-danger">Excluir</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="alert alert-info">Nenhum produto disponível no momento.</p>
{% endif %}

<a href="{% url 'catalog_BurguerApp:product_create' %}" class="btn btn-success">Adicionar Novo Produto</a>

{% endblock %}

catalog_BurguerApp/templates/products/update.html
{% extends "base.html" %}

{% load custom_filters %}

{% block 'titulo' %}Atualizar Produto{% endblock %}

{% block 'content' %}
<h1 class="mb-4">Atualizar Produto</h1>

<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="mb-3">
            {% if field.name == 'offer' %}
            <div class="form-check form-switch">
                {{ field|add_class:"form-check-input" }}
                <label class="form-check-label" for="{{ field.id_for_label }}">
                    Disponível
                </label>
                {% if field.help_text %}
                <div class="form-text">{{ field.help_text }}</div>
                {% endif %}
            </div>
            {% else %}
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
            {{ field|add_class:"form-control" }}
            {% if field.help_text %}
                <div class="form-text">{{ field.help_text }}</div>
            {% endif %}
            {% endif %}
            
            {% for error in field.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
    <a href="{% url 'catalog_BurguerApp:product_detail' product.id %}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}