BurguerApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('catalog_BurguerApp.urls')),
    path('auth/', include('auth_BurguerApp.urls')),
    path('', views.home, name='home'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('profile/', views.user_profile, name='user_profile'),
]

handler404 = 'BurguerApp.views.custom_page_not_found'
handler500 = 'BurguerApp.views.custom_error'
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_BurguerApp/urls.py
from django.urls import path
from . import views

app_name = 'auth_BurguerApp'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
]

catalog_BurguerApp/urls.py
from django.http import request;
from django.urls import path;
from django.views.generic.base import RedirectView
from . import views

app_name = 'catalog_BurguerApp'

urlpatterns = [

    path("", RedirectView.as_view(pattern_name='auth_BurguerApp:login_view'), name='home'),
    path('produtos/', views.product_list, name='product_list'),
    path('produtos/<int:id>/', views.product_detail, name='product_detail'),
    path('produtos/criar/', views.product_create, name='product_create'),
    path('produtos/<int:id>/atualizar/', views.product_update, name='product_update'),
    path('produtos/<int:id>/excluir/', views.product_delete, name='product_delete'),

    path('categorias/', views.category_list, name='category_list'),
    path('categorias/<int:id>/', views.category_detail, name='category_detail'),
    path('categorias/criar/', views.category_create, name='category_create'),
    path('categorias/<int:id>/atualizar/', views.category_update, name='category_update'),
    path('categorias/<int:id>/excluir/', views.category_delete, name='category_delete'),
]

templates/includes/layout/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/includes/layout/navbar_public.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(235 229 215 / 90%)">
    <div class="container">
        <a class="navbar-brand custom-brand" href="{% url 'home' %}">BurguerApp</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'user_profile' %}">Perfil</a></li>
                            {% if user.is_staff %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'catalog_BurguerApp:product_list' %}">Acesso ao Sistema</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'auth_BurguerApp:logout_view' %}">Sair</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'auth_BurguerApp:login_view' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href="{% url 'auth_BurguerApp:register_view' %}">Registrar</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<style>
    
.navbar-dark .navbar-nav .nav-link {
    color: #FB4937; 
    background-color: transparent !important; 
    text-decoration: none; 
    padding: 0.5rem 1rem; 
    transition: background-color 0.3s ease, color 0.3s ease; 
}

.btn-outline-primary::hover {
    background: transparent;
}


.navbar-dark .navbar-nav .nav-link:hover {
   background-color: rgb(235 209 215 / 90%);
    color: white; 
}


.navbar-dark .navbar-nav .nav-link:hover {
    color: #FF6347; 
}
    .custom-brand {
        color: #131313;
        text-decoration: none; 
        transition: color 0.3s ease; 
    }

    .custom-brand:hover {
        color: #ff6347; 
    }

    .navbar-dark .navbar-nav .nav-link:hover {
        color: black; 
        
    }

    
    .navbar-dark .navbar-toggler {
        
    }

    .navbar-dark .navbar-toggler-icon {
        color: #FB4937; 
    }
</style>

templates/includes/layout/scripts.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/includes/layout/tabs_admin.html
{% if request.resolver_match and request.resolver_match.namespace == 'catalog_BurguerApp' %}
<div class="container mt-4">
    <ul class="nav nav-tabs" id="adminTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a 
                class="nav-link {% if request.resolver_match.view_name == 'catalog_BurguerApp:product_list' %}active{% endif %}" 
                id="products-tab" 
                href='{% url 'catalog_BurguerApp:product_list' %}'
                role="tab" 
                aria-controls="products" 
                aria-selected="true">
                Produtos
            </a>
        </li>
        <li class="nav-item" role="presentation">
            <a 
                class="nav-link {% if request.resolver_match.view_name == 'catalog_BurguerApp:category_list' %}active{% endif %}" 
                id="categories-tab" 
                href="{% url 'catalog_BurguerApp:category_list' %}"
                role="tab" 
                aria-controls="categories"
                aria-selected="false">
                Categorias
            </a>
        </li>
    </ul>
</div>
{% endif %}